UF-3071: Create integration for updating status of a case.
Sundsvallskommun/process-engine-parking-permit pull request #17
Opened 2022-10-07 07:27 UTC by MickeWallner

2022-10-07 08:25 UTC, MattiasGradinApendo requested changes
Looks good, just fix the uncommented lines :)

2022-10-07 08:25 UTC, MattiasGradinApendo commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorker.java
> +//@ExternalTaskSubscription("caseData")
You forgot to uncomment this line

2022-10-07 08:30 UTC, foobar-1337 commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/casedata/CaseDataClient.java
> +	@GetMapping(path = "/errands/{errandId}", produces = APPLICATION_JSON_VALUE, consumes = APPLICATION_JSON_VALUE)
This method doesn't consume json

2022-10-07 08:30 UTC, foobar-1337 commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/casedata/configuration/CaseDataConfiguration.java
> +
Excessive use of newlines.

2022-10-07 08:30 UTC, foobar-1337 commented on src/test/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorkerTest.java
> +    CaseDataClient mockCaseDataClient;
private?

2022-10-07 08:30 UTC, foobar-1337 commented on src/test/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorkerTest.java
>      CitizenClient mockCitizenClient;
private?

2022-10-07 08:30 UTC, foobar-1337 commented on src/test/java/se/sundsvall/processengine/parkingpermit/integration/camunda/DecisionWorkerTest.java
>      DecisionWorker decisionWorker;
private?

(comment applicable for all member-fields in this class)

2022-10-07 08:30 UTC, foobar-1337 commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorker.java
> +//@ExternalTaskSubscription("caseData")
Why is this out-commented?
Remove instead?

Should it be "activated" again later on? Maybe add a "TODO" as well?

2022-10-07 08:30 UTC, foobar-1337 commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/DecisionWorker.java
> +//@ExternalTaskSubscription("updateDecision")
Why?

Should it be "activated" again later on? Maybe add a "TODO" as well?

2022-10-07 08:30 UTC, foobar-1337 commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/DecisionWorker.java
> +            ZoneOffset zoneOffSet= ZoneId.systemDefault().getRules().getOffset(LocalDateTime.now());
We have a util-method for this in dept44.

se.sundsvall.dept44.util.DateUtils.toOffsetDateTimeWithLocalOffset(OffsetDateTime date)

2022-10-07 12:19 UTC, MickeWallner commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorker.java
> +//@ExternalTaskSubscription("caseData")
Fixed

2022-10-07 12:19 UTC, MickeWallner commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/casedata/CaseDataClient.java
> +	@GetMapping(path = "/errands/{errandId}", produces = APPLICATION_JSON_VALUE, consumes = APPLICATION_JSON_VALUE)
Fixed

2022-10-07 12:19 UTC, MickeWallner commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/casedata/configuration/CaseDataConfiguration.java
> +
Fixed

2022-10-07 12:19 UTC, MickeWallner commented on src/test/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorkerTest.java
> +    CaseDataClient mockCaseDataClient;
Fixed

2022-10-07 12:20 UTC, MickeWallner commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/CaseDataWorker.java
> +//@ExternalTaskSubscription("caseData")
Just for be able to start locally. Forgot to uncomment. Fixed.

2022-10-07 12:21 UTC, MickeWallner commented on src/main/java/se/sundsvall/processengine/parkingpermit/integration/camunda/DecisionWorker.java
> +            ZoneOffset zoneOffSet= ZoneId.systemDefault().getRules().getOffset(LocalDateTime.now());
Fixed.

2022-10-08 12:37 UTC, MattiasGradinApendo approved these changes

2022-10-09 19:11 UTC, merged